service:
  name: kaskadi-webhooks-api

plugins:
  - serverless-aws-documentation

custom:
  documentation:
    api:
      info:
        version: 0.0.1
        title: ${self:service.name}
        description: YSWS webhooks API

provider:
  name: aws
  runtime: nodejs10.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  deploymentBucket:
    name: ${env:SLS_DEPLOY_BUCKET}
  deploymentPrefix: '@kaskadi/${self:service.name}'

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service.name}
  Outputs:
    RestAPIGatewayId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: KaskadiWebhooksRestAPIGatewayId
    RestAPIGatewayRootResourceId:
      Value: !GetAtt ApiGatewayRestApi.RootResourceId
      Export:
        Name: KaskadiWebhooksRestAPIGatewayRootResourceId

        # test
